version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: payments


  mongo-ui:
    image: mongo-express
    restart: always
    ports:
    - 1090:1090
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongo:27017
      PORT: 1090