version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-ui:
    image: mongo-express
    restart: always
    depends_on:
    - mongo
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongo:27017